env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx3g
    -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Run tests
      run: ./gradlew check
    - continue-on-error: true
      if: failure()
      name: Bundle the build report
      run: find . -type d -name 'reports' | zip -@ -r build-reports.zip
    - continue-on-error: true
      if: failure()
      name: Upload the build report
      uses: actions/upload-artifact@master
      with:
        name: error-report
        path: build-reports.zip
name: build_test
on:
  repository_dispatch:
    types: trigger-ga___pr.yml
